# Generated by Django 3.2.9 on 2021-11-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewContact',
        ),
    ]
