"""
Django settings for amo_test project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CONTENT_DIR = os.path.join(BASE_DIR, 'content')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nz^c+7m!v*czuk5qt&xqrjr)5c=&cf^4ol)-iz=#o^9608hw6*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amo_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath(CONTENT_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amo_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(CONTENT_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(CONTENT_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(CONTENT_DIR, 'assets'),
]

LOCALE_PATHS = [
    os.path.join(CONTENT_DIR, 'locale')
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#AmoCRM
ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUxYWRhZThiMzE0ZjkzMTExNjZiYmZmNjI5ZmIyNGY5MmRiMjdjODE1NTMxYTNjMjAwOTgxYjcwZDhjYTE3NWRkNmQzOTJkNDZhM2VhNGRkIn0.eyJhdWQiOiJkMDM1Mzk5OS02NzM4LTQ4NGUtYWQxZC05ZTE0NzYxNjUzZjMiLCJqdGkiOiI1MWFkYWU4YjMxNGY5MzExMTY2YmJmZjYyOWZiMjRmOTJkYjI3YzgxNTUzMWEzYzIwMDk4MWI3MGQ4Y2ExNzVkZDZkMzkyZDQ2YTNlYTRkZCIsImlhdCI6MTYzNjU2MTQ1NiwibmJmIjoxNjM2NTYxNDU2LCJleHAiOjE2MzY2NDc4NTYsInN1YiI6Ijc2MTI1MzEiLCJhY2NvdW50X2lkIjoyOTgwNjY2MCwic2NvcGVzIjpbInB1c2hfbm90aWZpY2F0aW9ucyIsImNybSIsIm5vdGlmaWNhdGlvbnMiXX0.kgiFUhQ0j0yA0EOH8zDcrC_sThwkAYTrrZ5_bmUdvgSbwm6WhtW8mBiCGGqRXxS1d7dSW_Nksptumv8rkznx_rTzmnBW9PzoSp_Lm77BwJ1_JXHO3STrFBUvFyNCDXjgkJruqq6q-s8zDxhfvvpxbtMU6ZAmE0NxssjajJUkMA6P0dJIuVIIfEfMYXvTPL7yjiQjN-lmMwUirF5p3VL4GFZpEkofebwGkWxDeOizJKRkggEDeih0OLnvLs2E-I4ViuP5Oa8IOSrpysXhN2bDEXTxeP5G1FmBVJU_TOjQTgP2mo4UUycCJ829mu184nEL8RLW-2BDqZZa6W_S_7rEcg'
