"""
Django settings for amo_test project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CONTENT_DIR = os.path.join(BASE_DIR, 'content')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nz^c+7m!v*czuk5qt&xqrjr)5c=&cf^4ol)-iz=#o^9608hw6*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'contact',
    'webhook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amo_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath(CONTENT_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amo_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(CONTENT_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(CONTENT_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(CONTENT_DIR, 'assets'),
]

LOCALE_PATHS = [
    os.path.join(CONTENT_DIR, 'locale')
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#AmoCRM
URL = 'https://usatest.amocrm.com'
CLIENT_ID = "21bf8f82-cea7-4dd7-abcf-2e2b90f66573"
CLIENT_SECRET = "bwBfNHj1EYektOecaPwQt7UbmTfl6t9aAo8EBUN3ITn6LnQexs7NxVM1g0q6Xu47"
REDIREKT_URI = "https://shopos.pro"
CODE = 'def502009afd60f72200a0364d2bafeadcd64fd480d414edd3b27e815d0ddf1a006c2f2666a79edc7e5731970b3e8e8fd8ade68b7b1ff872d42dfe5cad798e77bc65ea8d736b24062a8323654d8abf2fb13ed270fdb3eaf13814862755a609b3eb3dae2376cfb5399e16581424e60311878fd0d77e351368caea8b1a2afa746427f8c1fcca6fd7d83765fb2336dfee363e83cae218336dc95c75f548f0406b58d9fc79b4e8d46ac3d880f48352c06145d4e0d8ed8d20dd713555625f880520f13d40ae9cbf34f4cf11277dbd5b1d80cb7cdcd7da5508828b23bf7b0a841e79f4c861ff8444feebc5c43752f5068776c4fa750c80dee9d0c1c69d768d0f6965c421acb3376e548a931e1b243785eca0a4340771263641e5f14ac6bce946d161d42e292b7ed7dc62915c6e509bd46025e024c48d949830a103c960b98b8b327af7ed543eeaf8e69d05b89aabd54846eb9381015c466d7cb2bf66018b4621b5483ebd91cc9b2cdae599f157859a9780283a59bad0f81c5c686508345c64625fbc48054c730b406dc748f33caa468259a272b5af1d95ebe4dbc303565cb41007a05f9f5f964c92f719518f1a9cb8cd1ed228919298c73f9b1723364d0f20'
